### ISSUE TITLE
Add a Parser for Page

### ISSUE THREAD

**Issue by PonteIneptique** [HTR-United/htr-united-metadata-generator#2]
It might be interesting for either @FloChiff or @alix-tz ?

The way I implemented the script, you just need to create a new `Parser()` then declare it as an option
https://github.com/HTR-United/htr-united-metadata-generator/blob/2c1e81d177a58d11bf0aebe71dbf06a84ad7b638/humg.py#L111

And add a condition here:
https://github.com/HTR-United/htr-united-metadata-generator/blob/2c1e81d177a58d11bf0aebe71dbf06a84ad7b638/humg.py#L114-L115

**Comment by alix-tz** [comment]
It should be too complicated, I'll try to offer a PR soon!

**Comment by PonteIneptique** [comment]
Great, we'll make it a Clérice and Chagué production for the publication ;)
